quarkus.application.name=distributed-job-scheduler
quarkus.log.decorate-stacktraces=false
quarkus.devservices.enabled=true
quarkus.live-reload.enabled=true

# Logging
quarkus.log.category."io.github.hstefanov1.distributed.jobscheduler".level=DEBUG

# Datasource
quarkus.hibernate-orm.database.default-schema=job_scheduler
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.port=5432
quarkus.datasource.dev-ui.enabled=true
quarkus.datasource.devservices.init-script-path=liquibase/devservices/init.sql

# Liquibase
quarkus.liquibase.enabled=true
quarkus.liquibase.default-schema-name=job_scheduler
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.liquibase-schema-name=public
quarkus.liquibase.change-log=liquibase/changelog/master.xml
